name: mol_bayes
channels:
  - conda-forge
dependencies:
  - python=3.6
  - ipython=6.5
  - jupyter=1.0.0
  - matplotlib=3.0.2
  - pymc3=3.8
  - seaborn=0.9
  - numpy=1.15
  - scipy=1.1
  - pip:
    - git+git://github.com/arviz-devs/arviz.git

